# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [82]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 
list_1 = [50, 60, 70, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 70, 80, 100, 200, 300, 500, 600]

In [83]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  70,  80, 100, 200, 300, 500, 600])

In [84]:
type(my_numpy_array)

numpy.ndarray

In [85]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [86]:
example_matrix = np.array([[3, 7, 9, 3], [4 , 3, 2, 2]])
example_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [87]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.90034923, 0.2147656 , 0.61261042, 0.47617664, 0.06370763,
       0.70113529, 0.58094516, 0.32750626, 0.68397992, 0.359363  ,
       0.97206947, 0.55351288, 0.10930018, 0.25353033, 0.08146469,
       0.62294711, 0.95734773, 0.90325914, 0.95392593, 0.61534463])

In [88]:
# you can create a matrix of random number as well
x = np.random.rand(3, 3)
x

array([[0.07346041, 0.66856586, 0.81564865],
       [0.71009115, 0.50156714, 0.10326067],
       [0.39538961, 0.9638458 , 0.59455549]])

In [89]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

21

In [90]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([21, 12, 93, 77, 87, 36, 87, 46, 82, 37, 92, 98, 99, 39, 21],
      dtype=int32)

In [91]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [93]:
# Matrix of ones
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [94]:
# Array of zeros
x = np.zeros((8))
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [95]:
m = int(input("Enter a number: "))
x = np.random.randint(1, m, 10)
x

array([5, 2, 3, 1, 2, 1, 5, 4, 6, 6], dtype=int32)

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [96]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [101]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [102]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])
z= np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [103]:
my_numpy_array = np.array([3, 5,7,9,11,13,15,17,19])
my_numpy_array

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [104]:
# Access specific index from the numpy array
my_numpy_array[0] # first element
my_numpy_array[1] # second element
#my_numpy_array[2] # third element
my_numpy_array[-1] # fourth element

np.int64(19)

In [105]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3] # first 5 elements

array([3, 5, 7])

In [106]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7, 11, 13, 15, 17, 19])

In [107]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[6, 9, 8, 9],
       [5, 6, 4, 6],
       [4, 4, 8, 2],
       [6, 8, 2, 6]], dtype=int32)

In [108]:
# Get a row from a mtrix
matrix[0] # first row
matrix[1] # second row
matrix[-1] # last row

array([6, 8, 2, 6], dtype=int32)

In [109]:
# Get one element
matrix[0][0] # first row, first column

np.int32(6)

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [110]:
x = np.array([[2,30,20,-2,-4], [3,4,40,-3,2], [-3,4,-6,90,10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
x[4] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3,  2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [111]:
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[9, 3, 2, 7],
       [7, 9, 2, 9],
       [7, 6, 6, 2],
       [1, 1, 3, 9]], dtype=int32)

In [112]:
new_matrix = matrix[matrix > 3]
new_matrix

array([9, 7, 7, 9, 9, 7, 6, 6, 9], dtype=int32)

In [113]:
# Obtain odd elements only
#new_matrix = matrix [ matrix % 2 != 0]
new_matrix = matrix [ matrix % 2 == 1]
new_matrix

array([9, 3, 7, 7, 9, 9, 7, 1, 1, 3, 9], dtype=int32)

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [114]:
x = np.array([[2, 30, 20, -2, -4], [3, 4,  40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [115]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [116]:
import pandas as pd

In [117]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({
    'Bank Client ID': [111, 222, 333, 444],
    'Bank Client Name': ['John', 'Mary', 'Peter', 'Sam'],
    'Net Worth [$]': [3500, 29000, 100000, 2000],
    'Years with Bank': [2, 5, 10, 1]
})
bank_client_df

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111             John           3500                2
1             222             Mary          29000                5
2             333            Peter         100000               10
3             444              Sam           2000                1

In [118]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [119]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111             John           3500                2
1             222             Mary          29000                5

In [120]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
2             333            Peter         100000               10
3             444              Sam           2000                1

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [121]:
portfolio_df = pd.DataFrame({
    'stock ticker symbol': ['AAPL', 'AMZN', 'T'],
    'num of stocks': [ 3, 4, 9],
    'price per share': [3500, 29000, 100000]
})
portfolio_df

  stock ticker symbol  num of stocks  price per share
0                AAPL              3             3500
1                AMZN              4            29000
2                   T              9           100000

In [122]:
stocks_dollar_value = portfolio_df['num of stocks'] * portfolio_df['price per share']
stocks_dollar_value.sum()

np.int64(1026500)

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [123]:
# Pandas is used to read a html file and store data in a DataFrame
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %
8,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

In [124]:
# Read tabular data using read_html
house_price_df[1]

,Province,Average House Price,12 Month Change
0,British Columbia,"$736,000",+ 7.6 %
1,Ontario,"$594,000",– 3.2 %
2,Alberta,"$353,000",– 7.5 %
3,Quebec,"$340,000",+ 7.6 %
4,Manitoba,"$295,000",– 1.4 %
5,Saskatchewan,"$271,000",– 3.8 %
6,Nova Scotia,"$266,000",+ 3.5 %
7,Prince Edward Island,"$243,000",+ 3.0 %
8,Newfoundland / Labrador,"$236,000",– 1.6 %
9,New Brunswick,"$183,000",– 2.2 %
10,Canadian Average,"$488,000",– 1.3 %
11,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

In [125]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (5.4.0)

In [126]:
!python -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (25.1.1)

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [136]:
%pip install requests beautifulsoup4

import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'https://www.ssa.gov/oact/progdata/nra.html'
headers = {'User-Agent': 'Mozilla/5.0'}

# Request the page using requests
response = requests.get(url, headers=headers)
response.raise_for_status()  # Optional: raises error if status != 200

# Parse the page using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Extract tables using pandas
tables = pd.read_html(str(soup))

# Access the first table
retirement_df

Requirement already satisfied: requests in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.13.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sja\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

C:\Users\SJA\AppData\Local\Temp\ipykernel_26400\3603045633.py:18: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(str(soup))

,Year of birth,Age
0,1937 and prior,65
1,1938,65 and 2 months
2,1939,65 and 4 months
3,1940,65 and 6 months
4,1941,65 and 8 months
5,1942,65 and 10 months
6,1943-54,66
7,1955,66 and 2 months
8,1956,66 and 4 months
9,1957,66 and 6 months
10,1958,66 and 8 months
11,1959,66 and 10 months
12,1960 and later,67
13,Notes: 1. Persons born on January 1 of any yea...,Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [137]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [139]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5]
df_loyal

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [141]:
# Delete a column from a DataFrame
del bank_client_df['Bank client ID']
bank_client_df

  Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [146]:
df_networth = bank_client_df[bank_client_df['Net worth [$]']>=5000]
df_networth

  Bank Client Name  Net worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [147]:
df_networth['Net worth [$]'].sum()

np.int64(39000)

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake)

In [ ]:
# You can apply a function to the DataFrame

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# You can sort the values in the dataframe according to number of years with bank

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True

In [ ]:
# Set inplace = True to ensure that change has taken place in memory

In [ ]:
# Note that now the change (ordering) took place

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

array([ 1, 52,  8,  6, 50,  7, 14, 46, 27, 49], dtype=int32)

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [ ]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

  stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

HTTPError: HTTP Error 403: Forbidden

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df